before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev python3-dev libmemcached-dev python3-setuptools libtiff5-dev libjpeg-dev zlib1g-dev libfreetype6-dev
  - ln -s /usr/include/freetype2 /usr/include/freetype

test:
  script:
    - python3 setup.py install
    - planadversity test
